//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBiblioteca.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class autor
    {
        public autor()
        {
            this.livro = new HashSet<livro>();
        }
    
        public int idAutor { get; set; }
        public string nome { get; set; }
        public string nacionalidade { get; set; }
        public System.DateTime nascimento { get; set; }
        public string ocupacao { get; set; }
        public string telefone { get; set; }
    
        public virtual ICollection<livro> livro { get; set; }
    }
}
